### ISSUE TITLE
"main.py: error: unrecognized arguments: --source_dataset fake_cityscapes --target_dataset foggy_cityscapes" Please help.

### ISSUE THREAD

**Issue by tilahun12** [jizefeng0810/SDA-OD#1]
![error](https://user-images.githubusercontent.com/50729468/156019336-9114c076-c7d1-4aaf-9581-78b2449ade2c.png)

**Comment by jizefeng0810** [comment]
The path named ‘SDA-OD/CenterNet/src’ is not existing in this repository. Please make sure to use our code.
